version: '3.8'

services:

  postgis_sotm:
    image: postgis/postgis:17-3.5
    ports: 
      - "5482:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      
  imposm:
    image: geopostcodes/imposm:1.2
    stdin_open: true  # Equivalent to -i
    tty: true         # Equivalent to -t
    volumes:
        - ./osm_data/:/osm_data   
        - ./mapping/:/mapping
    depends_on:
        - postgis_sotm
    deploy: 
        restart_policy:
            condition: on-failure
            delay: 3s
            max_attempts: 5
            window: 5s